### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/ActionBarActivity;

### ISSUE THREAD

**Issue by harmeetsingh-work** [Xiaofei-it/Hermes#13]
Getting error at runtime :

> java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/ActionBarActivity;
>                                                        at xiaofei.library.hermes.util.TypeUtils$1.<init>(TypeUtils.java:51)
>                                                        at xiaofei.library.hermes.util.TypeUtils.<clinit>(TypeUtils.java:48)
>                                                        at xiaofei.library.hermes.util.TypeCenter.register(TypeCenter.java:94)
>                                                        at xiaofei.library.hermes.Hermes.register(Hermes.java:71)
>                                                        at xiaofei.library.hermeseventbus.HermesEventBus.init(HermesEventBus.java:122)
>                                                        at com.cloudblocks.android.user.MainApplication.onCreate(MainApplication.java:44)
>                                                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
>                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
>                                                        at android.app.ActivityThread.-wrap1(ActivityThread.java)
>                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
>                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                        at android.os.Looper.loop(Looper.java:148)
>                                                        at android.app.ActivityThread.main(ActivityThread.java:5443)
>                                                        at java.lang.reflect.Method.invoke(Native Method)
>                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
>                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

I think its due to `add(ActionBarActivity.class);` in > xiaofei.library.hermes.util.TypeUtils.java

For temporarily solving this issue, I created a empty class  `android.support.v7.app.ActionBarActivity.java`  and extend to `AppCompatActivity` and my app starting running again :)

```
package android.support.v7.app;

/**
 * Created by blackadmin on 07/10/17.
 */

public class ActionBarActivity extends AppCompatActivity {
}
```

**Comment by Lxingzhi** [comment]
@blackadmin  解决了吗？

**Comment by sky-lijinbo** [comment]
我解决了

**Comment by bo8980233** [comment]
我也是这样解决的，建了一个android.support.v7.app空包，里面放了一个
public class ActionBarActivity extends AppCompatActivity {
}
这个空类。有时间研究研究aidl吧，这个太受制于人了。。。。。。。

**Comment by lndlazy** [comment]
我添加了还是不行。

**Comment by ghost** [comment]
一个库居然报这种低级依赖问题，耽误时间，换其他库了
