### ISSUE TITLE
Error with java.util.Date type

### ISSUE THREAD

**Issue by ghost** [Xiaofei-it/Hermes#4]
Android 5.1.0 on Genymotion.

This test case is just a little bit modification from Hermes demo.
Interface:

``` java
@ClassId("UserManager")
public interface IUserManager {

    @MethodId("getUser")
    String getUser();

    @MethodId("getDate1")
    Date getDate1();

    @MethodId("getDateText")
    String getDateText();

}
```

Implemantation:

``` java
@ClassId("UserManager")
public class UserManager implements IUserManager {

    private static UserManager sInstance = null;

    private UserManager() {

    }

    public static synchronized UserManager getInstance() {
        if (sInstance == null) {
            sInstance = new UserManager();
        }
        return sInstance;
    }

    @MethodId("getUser")
    @Override
    public String getUser() {
        return "Xiaofei";
    }
    @MethodId("getDate1")
    @Override
    public Date getDate1() {
        return new Date();
    }
    @MethodId("getDateText")
    @Override
    public String getDateText() {
        return "DateText";
    }
}
```

Client side code:

``` java
IUserManager userManager = Hermes.getInstanceInService(HermesService.HermesService1.class, IUserManager.class);
                Date date = userManager.getDate1();
```

Exception stacktrace:

``` java
07-23 02:33:25.976  11397-11414/xiaofei.library.hermestest:g W/System.err﹕ xiaofei.library.hermes.util.HermesException
07-23 02:33:25.976  11397-11414/xiaofei.library.hermestest:g W/System.err﹕ at xiaofei.library.hermes.util.TypeCenter.getClassType(TypeCenter.java:145)
07-23 02:33:25.976  11397-11414/xiaofei.library.hermestest:g W/System.err﹕ at xiaofei.library.hermes.receiver.InstanceGettingReceiver.<init>(InstanceGettingReceiver.java:44)
07-23 02:33:25.976  11397-11414/xiaofei.library.hermestest:g W/System.err﹕ at xiaofei.library.hermes.receiver.ReceiverDesignator.getReceiver(ReceiverDesignator.java:35)
07-23 02:33:25.976  11397-11414/xiaofei.library.hermestest:g W/System.err﹕ at xiaofei.library.hermes.HermesService$1.send(HermesService.java:48)
07-23 02:33:25.976  11397-11414/xiaofei.library.hermestest:g W/System.err﹕ at xiaofei.library.hermes.internal.IHermesService$Stub.onTransact(IHermesService.java:70)
07-23 02:33:25.976  11397-11414/xiaofei.library.hermestest:g W/System.err﹕ at android.os.Binder.execTransact(Binder.java:446)
07-23 02:33:25.979  11380-11380/? E/HERMES﹕ Error occurs during getting instance. Error code: 16
07-23 02:33:25.979  11380-11380/? E/HERMES﹕ Error message: Cannot find class with ClassId annotation on it. ClassId = UserManager. Please add the same annotation on the corresponding class in the remote process and register it. Have you forgotten to register the class?
07-23 02:33:25.979  11380-11380/? D/AndroidRuntime﹕ Shutting down VM
07-23 02:33:25.979  11380-11380/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: xiaofei.library.hermestest:h, PID: 11380
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Date xiaofei.library.hermestest.IUserManager.getDate1()' on a null object reference
            at xiaofei.library.hermestest.DemoActivity$4.onClick(DemoActivity.java:71)
            at android.view.View.performClick(View.java:4780)
            at android.view.View$PerformClick.run(View.java:19866)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by ghost** [comment]
Sorry. This is my mistake. Close this issue.
